output "aurora_endpoint" {
  description = "Aurora cluster writer endpoint"
  value       = aws_rds_cluster.main.endpoint
}

output "aurora_reader_endpoint" {
  description = "Aurora cluster reader endpoint"
  value       = aws_rds_cluster.main.reader_endpoint
}

output "db_secret_arn" {
  description = "Secrets Manager ARN for DB credentials"
  value       = aws_secretsmanager_secret.db_credentials.arn
}

output "mcp_server_function_name" {
  description = "MCP server Lambda function name"
  value       = aws_lambda_function.mcp_server.function_name
}

output "mcp_server_function_url" {
  description = "MCP server Lambda function URL (IAM auth)"
  value       = aws_lambda_function_url.mcp_server.function_url
}

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = aws_subnet.private[*].id
}

# ── Copy key values to .env for local agent use ───────────
resource "local_file" "agent_env" {
  filename = "${path.module}/../agents/.env"
  content  = <<-EOT
    # Auto-generated by Terraform - do not edit manually
    AWS_REGION=${var.aws_region}
    DB_SECRET_ARN=${aws_secretsmanager_secret.db_credentials.arn}
    MCP_FUNCTION_NAME=${aws_lambda_function.mcp_server.function_name}
    MCP_FUNCTION_URL=${aws_lambda_function_url.mcp_server.function_url}
    BEDROCK_MODEL_ID=${var.bedrock_model_id}
    AURORA_ENDPOINT=${aws_rds_cluster.main.endpoint}
  EOT
}
